name: pase
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda
  - conda-libmamba-solver
  - pip
  - numpy
  - pandas
  - conda-forge::vtk>=9.3,<9.5
  - conda-forge::vtk-base>=9.3,<9.5
  - conda-forge::vtk-io-ffmpeg>=9.3,<9.5
  - trimesh
  - rtree
  - windrose
  - scipy
  - pvlib-python
  - pyvista
  - pip:
    - embreex
  - pyyaml
  - seaborn
  - yaml
  - pytest
  - pytest-cov
  - xmltodict
  - unidecode
