name: pase
channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda==23.3.1
  - conda-libmamba-solver==23.3.0
  - pip
  - numpy
  - pandas
  - vtk
  - trimesh
  - rtree
  - windrose
  - pvlib
  - pyembree
  - pyvista
  - pyyaml
  - seaborn
  - yaml
  - pytest
  - pytest-cov
