import numpy as np
import pyvista as pv
from collections import Counter, defaultdict
from typing import Dict, Iterable, List, Tuple


def compare_polydata(
    a: pv.PolyData,
    b: pv.PolyData,
    *,
    tol: float = 1e-4,
    ignore_point_order: bool = True,
    ignore_cell_order: bool = True,
    ignore_orientation: bool = True,
    compare_point_data: bool = False,
    compare_cell_data: bool = False,
) -> bool:
    """
    Compare two :class:`pyvista.PolyData` objects for geometric, topological,
    and (optionally) data-field equality, within a numerical tolerance.

    This function is designed for **unit testing and regression validation**
    of PASE 3D geometry outputs (e.g. PV panels, meshes, or irradiance surfaces).
    It determines whether two PolyData objects represent the same shape,
    connectivity, and optional point/cell data, under flexible invariance conditions.

    Parameters
    ----------
    a : pv.PolyData
        First mesh to compare.
    b : pv.PolyData
        Second mesh to compare.
    tol : float, optional
        Absolute tolerance for coordinate and floating-point comparisons.
        Default is `1e-6`.
    ignore_point_order : bool, optional
        If `True`, the comparison is invariant to the order of points.
        Points are matched based on spatial proximity within the tolerance.
        Default is `True`.
    ignore_cell_order : bool, optional
        If `True`, the order of cells (faces) is ignored.
        The two meshes are compared as multisets of normalized cell definitions.
        Default is `True`.
    ignore_orientation : bool, optional
        If `True`, cell orientation (clockwise vs. counterclockwise) is ignored.
        Default is `True`.
    compare_point_data : bool, optional
        If `True`, corresponding point data arrays (e.g., irradiance values)
        are also compared. Default is `False`.
    compare_cell_data : bool, optional
        If `True`, corresponding cell data arrays are also compared.
        Default is `False`.

    Returns
    -------
    bool
        `True` if both PolyData objects are equivalent under the specified
        invariance conditions; `False` otherwise.

    Notes
    -----
    - The comparison is **strict** on geometry and topology: mismatched
      coordinates, cell definitions, or array dimensions will cause failure.
    - Use this function in PASE tests to ensure consistency of geometric
      outputs generated by modules such as:
        - `pase.ENVIRONMENT.mesh`
        - `pase.ENVIRONMENT.light`
        - `pase.PHOTOVOLTAICS.configuration`
    - The implementation does not modify input data.

    Examples
    --------
    >>> import pyvista as pv
    >>> from pase.tests.utils import compare_polydata

    >>> a = pv.Plane()
    >>> b = a.copy()
    >>> compare_polydata(a, b)
    True

    >>> b.points += 1e-4
    >>> compare_polydata(a, b, tol=1e-6)
    False

    >>> compare_polydata(a, b, tol=1e-3)
    True
    """
    # --- fast shape check ---
    if a.n_points != b.n_points or a.n_cells != b.n_cells:
        return False

    # --- build point-index mapping A->B ---
    if not ignore_point_order:
        if not np.allclose(a.points, b.points, atol=tol, rtol=0):
            return False
        point_map = np.arange(a.n_points, dtype=np.int64)
    else:
        def key_coords(P: np.ndarray):
            nd = max(0, int(np.ceil(-np.log10(tol)))) if tol > 0 else 12
            return map(tuple, np.round(P, nd))
        buckets: Dict[Tuple[float,float,float], List[int]] = defaultdict(list)
        for j, k in enumerate(key_coords(b.points)):
            buckets[k].append(j)
        point_map = np.empty(a.n_points, dtype=np.int64)
        for i, k in enumerate(key_coords(a.points)):
            lst = buckets.get(k)
            if not lst:
                return False
            point_map[i] = lst.pop()
        if not np.allclose(a.points, b.points[point_map], atol=tol, rtol=0):
            return False

    # --- connectivity helpers ---
    def faces_to_cells(poly: pv.PolyData) -> List[List[int]]:
        """Convert PyVista face array to list of cell vertex indices."""
        arr = poly.faces
        out: List[List[int]] = []
        i, n = 0, arr.size
        while i < n:
            k = int(arr[i])
            out.append([int(x) for x in arr[i+1:i+1+k]])
            i += 1 + k
        return out

    def normalize_cell(ids: List[int]) -> Tuple[int, ...]:
        """Normalize a polygon cell by rotation and (optional) orientation."""
        if not ids:
            return tuple()
        ids = list(ids)
        m = min(ids)
        j = ids.index(m)
        rot = ids[j:] + ids[:j]
        if ignore_orientation and len(rot) >= 2:
            rev = [rot[0]] + list(reversed(rot[1:]))
            return tuple(min(rot, rev))
        return tuple(rot)

    # --- prepare cells for both meshes ---
    cells_b_raw = faces_to_cells(b)
    cells_b_norm = [normalize_cell(c) if ignore_orientation else tuple(c) for c in cells_b_raw]

    cells_a_raw = faces_to_cells(a)
    cells_a_mapped = [[int(point_map[idx]) for idx in cell] for cell in cells_a_raw]
    cells_a_norm = [normalize_cell(c) if ignore_orientation else tuple(c) for c in cells_a_mapped]

    # --- connectivity compare ---
    if ignore_cell_order:
        if Counter(cells_a_norm) != Counter(cells_b_norm):
            return False
    else:
        if len(cells_a_norm) != len(cells_b_norm):
            return False
        if any(x != y for x, y in zip(cells_a_norm, cells_b_norm)):
            return False

    # --- optional: point_data ---
    if compare_point_data:
        a_pd, b_pd = a.point_data, b.point_data
        if set(a_pd.keys()) != set(b_pd.keys()):
            return False
        for k in a_pd.keys():
            A = np.asarray(a_pd[k])
            B = np.asarray(b_pd[k])
            if A.shape != B.shape:
                return False
            if A.dtype.kind in "fc":
                if not np.allclose(A, B if not ignore_point_order else B[point_map], atol=tol, rtol=0):
                    return False
            else:
                if not np.array_equal(A, B if not ignore_point_order else B[point_map]):
                    return False

    # --- optional: cell_data ---
    if compare_cell_data:
        a_cd, b_cd = a.cell_data, b.cell_data
        if set(a_cd.keys()) != set(b_cd.keys()):
            return False
        if ignore_cell_order:
            from collections import defaultdict as dd
            def rows_multiset(poly: pv.PolyData, cells_norm: List[Tuple[int, ...]]):
                ms = dd(list)
                for row, key in zip(poly.cell_data.values(), cells_norm):
                    ms[key].append(np.array(row))
                for k in ms:
                    ms[k] = sorted(ms[k], key=lambda x: (x.shape, x.tobytes()))
                return ms
            ms_a = rows_multiset(a, cells_a_norm)
            ms_b = rows_multiset(b, cells_b_norm)
            if set(ms_a.keys()) != set(ms_b.keys()):
                return False
            for k in ms_a:
                if len(ms_a[k]) != len(ms_b[k]):
                    return False
                for ra, rb in zip(ms_a[k], ms_b[k]):
                    if ra.dtype.kind in "fc":
                        if not np.allclose(ra, rb, atol=tol, rtol=0):
                            return False
                    else:
                        if not np.array_equal(ra, rb):
                            return False
        else:
            for k in a_cd.keys():
                A = np.asarray(a_cd[k]); B = np.asarray(b_cd[k])
                if A.shape != B.shape:
                    return False
                if A.dtype.kind in "fc":
                    if not np.allclose(A, B, atol=tol, rtol=0):
                        return False
                else:
                    if not np.array_equal(A, B):
                        return False

    return True
def _ensure_polydata(obj) -> pv.PolyData:
    if isinstance(obj, pv.PolyData):
        return obj
    if hasattr(obj, "extract_surface"):
        return obj.extract_surface()
    return pv.wrap(obj).extract_surface()

def merge_multiblock_to_poly(mb) -> pv.PolyData:
    """Merge any MultiBlock into a single PolyData."""
    if hasattr(mb, "n_blocks"):
        polys = [mb[i] for i in range(mb.n_blocks)]
    else:
        # fallback for iterables that don't expose n_blocks
        polys = list(mb)
    return pv.merge([_ensure_polydata(p) for p in polys], merge_points=True)

