#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 11 09:16:49 2023

@author: nicolasdecock
"""

import numpy as np
from vtk import vtkPointSet, vtkPoissonDiskSampler, vtkMaskPoints
import pyvista as pyV


'''
Class Mesh


This class aims to provide point sources which are used by the light_scene class 
in order to compute the diffuse and direct light at different points of the scene.
The class contains different "Add_" method which are specific specific for each application.
The user has to configure these methods and provide a flag which will be used
to latter on gather the points according to their nature. 


Example of use:
    
Initialization:
M = Mesh()

Addition of a regular mesh at the ground level:
M.Add_Plane_Ground_regular_meshes(0,1,0,3,0.1,1)

Addition of a mesh from a PV panel geometry:
M.Add_PV_Mesh(first_panel)

Addition of a sensor:
M.Add_Sensor(0,1,1,"Pyranometre")

Retrieve of point sources generated by the previous "Add" methods:
S = M.Get_SourcePoints()

Retrieve of dictionnary providing the mapping between the flagID and the flag
Dict = M.Get_SourcesDict()


'''

class Mesh:
    def __init__(self,AutoMerge = True):
        
        #Attribut par encore utilise mais ayant pour but de fusionner les sources ayant le meme flag en leur attribuant le meme flagID
        self.AutoMerge = AutoMerge
        
        
        self.SourcesPoints = np.empty((0, 4))
        self.SourcesDict = {}
        self.SourcesDictKey = 0

    #Public
    def Add_Plane_Ground_regular_meshes(self, X_min, X_max, Y_min, Y_max, X_increment, Y_increment,flag = "ground", zcoord = 0):
        xrng = np.arange(X_min, X_max, X_increment)
        yrng = np.arange(Y_min, Y_max, Y_increment)
        zrng = zcoord
        # Create coordinate arrays for each dimension using meshgrid
        x_coords, y_coords, z_coords = np.meshgrid(xrng, yrng, zrng, indexing='ij')
        
        # Stack the coordinate arrays to create an array of coordinates
        coordinates = np.stack((x_coords, y_coords, z_coords), axis=-1)
        
        # Reshape the coordinates to a 2D array (number of coordinates, number of dimensions)
        coordinates_2d = coordinates.reshape(-1, coordinates.shape[-1])

        self.Add_SourcesPoints(coordinates_2d,flag)
   
    #Private
    def Get_Surface_Sample_Points(self,OPolyData,radius=0.05,Filter="Poisson",MaxSubdivide=6):
        # PolyDataArea = abs((OPolyData.GetBounds()[0]-OPolyData.GetBounds()[1])*(OPolyData.GetBounds()[3]-OPolyData.GetBounds()[4]))
        # NCells = len(OPolyData.cell)
        SuperSampleData = OPolyData.subdivide(MaxSubdivide)
        if Filter == "Random":
            Mask = vtkMaskPoints()
            Mask.SetRandomModeType(4) #4 --> uniform sampling
            Mask.SetInputData(SuperSampleData)
            Mask.Update()
        elif Filter == "Poisson":
            Mask = vtkPoissonDiskSampler() #Algorithm using darts like sampling
            Mask.SetInputData(SuperSampleData)
            Mask.SetRadius(radius)
            Mask.Update()
        else:
            print('Error Filter not correctly set Poisson or Random')
        return pyV.PointSet(vtkPointSet().SafeDownCast(Mask.GetOutputDataObject(0))).points
    
    
    #Public
    def Add_PV_Mesh(self,Geometry,radius = 0.05,flag = "PV"):
        coordinates_2d = self.Get_Surface_Sample_Points(Geometry,radius)
        self.Add_SourcesPoints(coordinates_2d,flag)
  
    #Private
    def Add_SourcesPoints(self,coordinates,flag):
        #Addition of the flagID column (fourth column)        
        coordinatesT = np.hstack((coordinates,np.ones((coordinates.shape[0], 1))*self.SourcesDictKey)) 
        self.SourcesPoints = np.concatenate((self.SourcesPoints, coordinatesT))
        self.SourcesDict[self.SourcesDictKey] = flag
        self.SourcesDictKey += 1

    #Public
    def Add_Sensor(self,x,y,z,flag):
        self.Add_SourcesPoints(np.array([[x,y,z]]),flag)

    #Public
    def Get_SourcePoints(self,FlagId=True):
        if FlagId:
            return self.SourcesPoints
        else:
            return self.SourcesPoints[:,:-1]
    
    #Public
    def Get_SourcesDict(self):
        return self.SourcesDict